== Apache Maven Jenkins Shared Libraries

This repository contains the Jenkins shared libraries that define the standard build process for Apache Maven subporjects.

The shared libraries rely on a definition of the per-Jenkins instance specific configuration details.
The definition of those instance specific configuration details as customized for the Apache build server is hosted in https://gitbox.apache.org/repos/asf?p=maven-jenkins-env.git[maven-jenkins-env]

If you want to build the Apache Maven repositories on your own Jenkins infrastructure you will need to define two shared libraries:

. The first shared library should be a clone of https://gitbox.apache.org/repos/asf?p=maven-jenkins-env.git[maven-jenkins-env.git] with the environment specifics modified to match your own Jenkins environment
. The second shared library should be this shared library which defines the standard Apache Maven build process

If you would like more information on the design of this Jenkinsfile structure see https://www.youtube.com/watch?v=s4w8BX3xi4M[Episode 4] and https://www.youtube.com/watch?v=vfAzhVDxOOk[Episode 5] of Stephen Connolly's "Watch Me Code" series.
